apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend
  labels:
    app: product-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-backend
  template:
    metadata:
      name: product-backend
      labels:
        app: product-backend
    spec:
      containers:
        - name: product-backend
          image: aimejean/product-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      