apiVersion: v1
kind: Service
metadata:
  name: product-backend-service
spec:
  selector:
    app: product-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010
  type: NodePort
  